DROP TRIGGER WORKDESK.OW_WORKSHEET_ATIS_INTEG_TR_AI;

CREATE OR REPLACE TRIGGER WORKDESK.OW_WORKSHEET_ATIS_INTEG_TR_AI
AFTER UPDATE OF STATUS ON WORKDESK.OW_WORKSHEET FOR EACH ROW
WHEN (NEW.STATUS = 'PUBLISHED' AND NEW.TYPE = 'WORKSHEET' AND NEW.NEW_OW = 'Y')
BEGIN

WORKDESK.APX_WOKDSK_PO_TOOLKIT.INSERTA_ATISPROD_WORKSHEET(:NEW.TK_OW,:NEW.SET_WRKSHT_NUM);


END OW_WORKSHEET_ATIS_INTEG_TR_AI;
/
