DROP TRIGGER WORKDESK.OW_WORKSHEET_SET_DESC_TRG_BIU;

CREATE OR REPLACE TRIGGER WORKDESK.OW_WORKSHEET_SET_DESC_TRG_BIU 
    BEFORE UPDATE OR INSERT ON WORKDESK.OW_WORKSHEET FOR EACH ROW
DECLARE
BEGIN
    IF TRIM(:NEW.DESCRIPTION) IS NULL THEN
        :NEW.DESCRIPTION := APX_WOKDSK_PO_TOOLKIT.PO_SET_SUPPLIER_DESCRIPTION(:NEW.SET_WRKSHT_NUM);
    END IF;     
END OW_WORKSHEET_SET_DESC_TRG_BIU;
/
