DROP SEQUENCE WORKDESK.SEQ_WORKSHEET_ODS;

CREATE SEQUENCE WORKDESK.SEQ_WORKSHEET_ODS
  START WITH 31141
  MAXVALUE 99999
  MINVALUE 10000
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  GLOBAL;


CREATE OR REPLACE PUBLIC SYNONYM SEQ_WORKSHEET_ODS FOR WORKDESK.SEQ_WORKSHEET_ODS;


GRANT ALTER, SELECT ON WORKDESK.SEQ_WORKSHEET_ODS TO PUBLIC;
