DROP TABLE WORKDESK.CM_DOC_PARTY_ROLE CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.CM_DOC_PARTY_ROLE
(
  ROLE_ID           VARCHAR2(32 BYTE)           NOT NULL,
  ROLE_NAME         VARCHAR2(48 BYTE)           NOT NULL,
  DESCR             VARCHAR2(64 BYTE),
  ACTIVE            VARCHAR2(1 BYTE)            DEFAULT 'Y'                   NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE CM_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.CM_DOC_PARTY_ROLE IS 'This table contains the roles for customer doc parties.';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.ROLE_ID IS 'The unique id of this role';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.ROLE_NAME IS 'The name of the role.';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.DESCR IS 'The description of the role.';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.ACTIVE IS 'Is the role assignable to doc parties?';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.CM_DOC_PARTY_ROLE.LAST_UPDATED_BY IS 'User id of the person that last updated the record.';


CREATE UNIQUE INDEX WORKDESK.PK_DOC_PARTY_ROLE ON WORKDESK.CM_DOC_PARTY_ROLE
(ROLE_ID)
LOGGING
TABLESPACE CM_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.CM_DOC_PARTY_ROLE ADD (
  CONSTRAINT PK_DOC_PARTY_ROLE
  PRIMARY KEY
  (ROLE_ID)
  USING INDEX WORKDESK.PK_DOC_PARTY_ROLE
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.CM_DOC_PARTY_ROLE TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.CM_DOC_PARTY_ROLE TO PUBLIC;
