DROP TABLE WORKDESK.CM_FAVORITE_CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.CM_FAVORITE_CUSTOMER
(
  TK_EMPLOYEE       NUMBER(15)                  NOT NULL,
  CUST_ACCOUNT_ID   NUMBER(15)                  NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE CM_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.CM_FAVORITE_CUSTOMER IS 'This table contains customers marked as favorites by users.';

COMMENT ON COLUMN WORKDESK.CM_FAVORITE_CUSTOMER.TK_EMPLOYEE IS 'The id of the employee.';

COMMENT ON COLUMN WORKDESK.CM_FAVORITE_CUSTOMER.CUST_ACCOUNT_ID IS 'The id of the customer.';

COMMENT ON COLUMN WORKDESK.CM_FAVORITE_CUSTOMER.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.CM_FAVORITE_CUSTOMER.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.CM_FAVORITE_CUSTOMER.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.CM_FAVORITE_CUSTOMER.LAST_UPDATED_BY IS 'User id of the person that last updated the record.';


CREATE UNIQUE INDEX WORKDESK.PK_CM_FAVORITE_CUSTOMER ON WORKDESK.CM_FAVORITE_CUSTOMER
(TK_EMPLOYEE, CUST_ACCOUNT_ID)
LOGGING
TABLESPACE CM_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.CM_FAVORITE_CUSTOMER ADD (
  CONSTRAINT PK_CM_FAVORITE_CUSTOMER
  PRIMARY KEY
  (TK_EMPLOYEE, CUST_ACCOUNT_ID)
  USING INDEX WORKDESK.PK_CM_FAVORITE_CUSTOMER
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.CM_FAVORITE_CUSTOMER TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.CM_FAVORITE_CUSTOMER TO PUBLIC;
