DROP TABLE WORKDESK.CM_GROUP_CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.CM_GROUP_CUSTOMER
(
  TK_GROUP          NUMBER(7)                   NOT NULL,
  CUST_ACCOUNT_ID   NUMBER(15)                  NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE CM_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.CM_GROUP_CUSTOMER IS 'This table contains the customers of AJC workgroups.';

COMMENT ON COLUMN WORKDESK.CM_GROUP_CUSTOMER.TK_GROUP IS 'The id of the group.';

COMMENT ON COLUMN WORKDESK.CM_GROUP_CUSTOMER.CUST_ACCOUNT_ID IS 'The id of the customer.';

COMMENT ON COLUMN WORKDESK.CM_GROUP_CUSTOMER.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.CM_GROUP_CUSTOMER.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.CM_GROUP_CUSTOMER.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.CM_GROUP_CUSTOMER.LAST_UPDATED_BY IS 'User id of the person that last updated the record.';


CREATE UNIQUE INDEX WORKDESK.PK_CM_GROUP_CUSTOMER ON WORKDESK.CM_GROUP_CUSTOMER
(TK_GROUP, CUST_ACCOUNT_ID)
LOGGING
TABLESPACE CM_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.CM_GROUP_CUSTOMER ADD (
  CONSTRAINT PK_CM_GROUP_CUSTOMER
  PRIMARY KEY
  (TK_GROUP, CUST_ACCOUNT_ID)
  USING INDEX WORKDESK.PK_CM_GROUP_CUSTOMER
  ENABLE VALIDATE);


ALTER TABLE WORKDESK.CM_GROUP_CUSTOMER ADD (
  CONSTRAINT FK_CM_GRPCUST_TK_GROUP 
  FOREIGN KEY (TK_GROUP) 
  REFERENCES WORKDESK.CM_GROUP (TK_GROUP)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.CM_GROUP_CUSTOMER TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.CM_GROUP_CUSTOMER TO PUBLIC;
