DROP TABLE WORKDESK.EMPLOYEE_ID CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.EMPLOYEE_ID
(
  DOMAIN_ID         VARCHAR2(64 BYTE)           NOT NULL,
  TK_EMPLOYEE       NUMBER(15)                  NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.EMPLOYEE_ID IS 'This table includes the mapings between ATIS ids and Domain ids.';

COMMENT ON COLUMN WORKDESK.EMPLOYEE_ID.DOMAIN_ID IS 'Id from domain';

COMMENT ON COLUMN WORKDESK.EMPLOYEE_ID.TK_EMPLOYEE IS 'Id in ATIS';


CREATE UNIQUE INDEX WORKDESK.PK_EMPLOYEE_ID ON WORKDESK.EMPLOYEE_ID
(DOMAIN_ID)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.EMPLOYEE_ID ADD (
  CONSTRAINT PK_EMPLOYEE_ID
  PRIMARY KEY
  (DOMAIN_ID)
  USING INDEX WORKDESK.PK_EMPLOYEE_ID
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM EMPLOYEE_ID FOR WORKDESK.EMPLOYEE_ID;


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.EMPLOYEE_ID TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.EMPLOYEE_ID TO PUBLIC;
