DROP TABLE WORKDESK.ERROR_WORKDESK_INT CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.ERROR_WORKDESK_INT
(
  ID     NUMBER(10),
  ERROR  VARCHAR2(1000 BYTE),
  FECHA  TIMESTAMP(6)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON WORKDESK.ERROR_WORKDESK_INT TO ATISPROD;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON WORKDESK.ERROR_WORKDESK_INT TO OMS;
