DROP TABLE WORKDESK.OW_CONTRACT_WORKSHEET CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_CONTRACT_WORKSHEET
(
  TK_CONTRACT       NUMBER(7)                   NOT NULL,
  TK_OW             NUMBER(7)                   NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15),
  INIT_TK_OW        NUMBER(7)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_CONTRACT_WORKSHEET IS 'This table indicates what worksheets are associated with a contract';

COMMENT ON COLUMN WORKDESK.OW_CONTRACT_WORKSHEET.TK_CONTRACT IS 'This is the id of the contract';

COMMENT ON COLUMN WORKDESK.OW_CONTRACT_WORKSHEET.TK_OW IS 'This is the id of the worksheet';

COMMENT ON COLUMN WORKDESK.OW_CONTRACT_WORKSHEET.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.OW_CONTRACT_WORKSHEET.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.OW_CONTRACT_WORKSHEET.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.OW_CONTRACT_WORKSHEET.LAST_UPDATED_BY IS 'User id of the person that last updated the record.';


CREATE UNIQUE INDEX WORKDESK.PK_CONTRACT_WORKSHEET ON WORKDESK.OW_CONTRACT_WORKSHEET
(TK_CONTRACT, INIT_TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_CONTRACT_WORKSHEET ADD (
  CONSTRAINT PK_CONTRACT_WORKSHEET
  PRIMARY KEY
  (TK_CONTRACT, INIT_TK_OW)
  USING INDEX WORKDESK.PK_CONTRACT_WORKSHEET
  ENABLE VALIDATE);


CREATE INDEX WORKDESK.IDX_TK_OW ON WORKDESK.OW_CONTRACT_WORKSHEET
(TK_OW)
LOGGING
TABLESPACE WORKDESK_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM OW_CONTRACT_WORKSHEET FOR WORKDESK.OW_CONTRACT_WORKSHEET;


ALTER TABLE WORKDESK.OW_CONTRACT_WORKSHEET ADD (
  CONSTRAINT FK_OW_CONTWRKS_TK_CONTRACT 
  FOREIGN KEY (TK_CONTRACT) 
  REFERENCES WORKDESK.OW_CONTRACT (TK_CONTRACT)
  ENABLE VALIDATE
,  CONSTRAINT FK_OW_CONTWRKS_TK_OW 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_CONTRACT_WORKSHEET TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_CONTRACT_WORKSHEET TO PUBLIC;
