DROP TABLE WORKDESK.OW_CONTRACT_TRANSFER CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_CONTRACT_TRANSFER
(
  TK_TRANSFER       NUMBER(7)                   NOT NULL,
  TK_CONTRACT       NUMBER(7)                   NOT NULL,
  TRANSFER_TO       NUMBER(15)                  NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WORKDESK.PK_CONTRACT_TRANSFER ON WORKDESK.OW_CONTRACT_TRANSFER
(TK_TRANSFER)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_CONTRACT_TRANSFER ADD (
  CONSTRAINT PK_CONTRACT_TRANSFER
  PRIMARY KEY
  (TK_TRANSFER)
  USING INDEX WORKDESK.PK_CONTRACT_TRANSFER
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_CONTRACT_TRANSFER FOR WORKDESK.OW_CONTRACT_TRANSFER;


ALTER TABLE WORKDESK.OW_CONTRACT_TRANSFER ADD (
  CONSTRAINT FK_OW_CONTTRANS_TK_CONTRACT 
  FOREIGN KEY (TK_CONTRACT) 
  REFERENCES WORKDESK.OW_CONTRACT (TK_CONTRACT)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_CONTRACT_TRANSFER TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_CONTRACT_TRANSFER TO PUBLIC;
