DROP TABLE WORKDESK.OW_EMPLOYEE_DATA CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_EMPLOYEE_DATA
(
  FIRST_NAME     VARCHAR2(1000 BYTE),
  LAST_NAME      VARCHAR2(1000 BYTE),
  ALIAS          VARCHAR2(1000 BYTE),
  EMAIL          VARCHAR2(1000 BYTE),
  WEIVER_REASON  VARCHAR2(1000 BYTE),
  PHONE_NUMBER   VARCHAR2(1000 BYTE),
  MOBILE_NUMBER  VARCHAR2(1000 BYTE)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
