DROP TABLE WORKDESK.OW_EMPLOYEE_WS_LIST CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_EMPLOYEE_WS_LIST
(
  TK_OW             NUMBER(7)                   NOT NULL,
  TK_EMPLOYEE       NUMBER(15)                  NOT NULL,
  TK_TRANSFER       NUMBER(15),
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_EMPLOYEE_WS_LIST IS 'This table includes the worksheets that should show in the list of worksheets for a user';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.TK_OW IS 'Worksheet ID';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.TK_EMPLOYEE IS 'Employee Id';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.TK_TRANSFER IS 'Id of the transfer (if the worksheet was transferred)';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.OW_EMPLOYEE_WS_LIST.LAST_UPDATED_BY IS 'User id of the person that last updated the record.';


CREATE UNIQUE INDEX WORKDESK.PK_WS_EMPLOYEE_LIST ON WORKDESK.OW_EMPLOYEE_WS_LIST
(TK_OW, TK_EMPLOYEE)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_EMPLOYEE_WS_LIST ADD (
  CONSTRAINT PK_WS_EMPLOYEE_LIST
  PRIMARY KEY
  (TK_OW, TK_EMPLOYEE)
  USING INDEX WORKDESK.PK_WS_EMPLOYEE_LIST
  ENABLE VALIDATE);


CREATE INDEX WORKDESK.I_OW_EMPLOYEE_WS_LIST_TK_EMP ON WORKDESK.OW_EMPLOYEE_WS_LIST
(TK_EMPLOYEE)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM OW_EMPLOYEE_WS_LIST FOR WORKDESK.OW_EMPLOYEE_WS_LIST;


ALTER TABLE WORKDESK.OW_EMPLOYEE_WS_LIST ADD (
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET (TK_OW)
  ENABLE VALIDATE
,  FOREIGN KEY (TK_TRANSFER) 
  REFERENCES WORKDESK.OW_WS_TRANSFER (TK_TRANSFER)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_EMPLOYEE_WS_LIST TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_EMPLOYEE_WS_LIST TO PUBLIC;
