DROP TABLE WORKDESK.OW_FIELD_REQ_EXCEPTION CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_FIELD_REQ_EXCEPTION
(
  TK_EMPLOYEE       NUMBER(7),
  FIELD_ID          VARCHAR2(20 BYTE),
  CREATION_DATE     DATE,
  CREATED_BY        VARCHAR2(30 BYTE),
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATE_BY    VARCHAR2(30 BYTE)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_FIELD_REQ_EXCEPTION TO OMS;
