DROP TABLE WORKDESK.OW_PUR_ORD_PUB CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_PUR_ORD_PUB
(
  TK_OW                 NUMBER(7)               NOT NULL,
  VENDOR_ID             NUMBER(15),
  PURCHASE_TERMS_DESCR  VARCHAR2(50 BYTE),
  PICKUP_PERIOD_DESCR   VARCHAR2(50 BYTE),
  CONTACT               VARCHAR2(100 BYTE),
  VND_ORD_NUM           VARCHAR2(25 BYTE),
  PAY_TERM_DESCR        VARCHAR2(25 BYTE),
  PURCHASE_DATE         DATE,
  TK_EMP_TRADER         NUMBER(15),
  TK_EMP_TRF            NUMBER(15),
  DISCOUNT_RATE         NUMBER(10,5),
  CURRENCY_CODE         VARCHAR2(15 BYTE),
  EXCHANGE_RATE         NUMBER(13,7)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_PUR_ORD_PUB IS 'This table includes Purchase header information for all published Worksheets/Templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.TK_OW IS 'This is the id for the Worksheet/Template.';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.VENDOR_ID IS 'This is the Supplier for the product.Code comes from po_vendors';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.PURCHASE_TERMS_DESCR IS 'Purchase Terms - This is the description of the purchase terms';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.PICKUP_PERIOD_DESCR IS 'Pickup Date - This is the date when the cargo will be picked up/shipped.';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.CONTACT IS 'Location/Contact - This is the Supplier Contact or location for the Order.';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.VND_ORD_NUM IS 'Sup Ref # - This is the Supplier Reference Number.';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.PAY_TERM_DESCR IS 'Purchase Pay Terms - This is the description of the payment terms (eg Wire Transfer in Advance, Open Account, etc.).';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.PURCHASE_DATE IS 'Purchase Date - Date of the Purchase';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.TK_EMP_TRADER IS 'PurchaserCode comes from a_employee';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.TK_EMP_TRF IS 'Traffic CordCode comes from a_employee';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.DISCOUNT_RATE IS 'Discount Percentage - This is the discount for the purchase.';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.CURRENCY_CODE IS 'Purchase Price Curr ';

COMMENT ON COLUMN WORKDESK.OW_PUR_ORD_PUB.EXCHANGE_RATE IS 'Rate ';


CREATE UNIQUE INDEX WORKDESK.PK_OW_PUR_ORD_PUB ON WORKDESK.OW_PUR_ORD_PUB
(TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_PUR_ORD_PUB ADD (
  CONSTRAINT PK_OW_PUR_ORD_PUB
  PRIMARY KEY
  (TK_OW)
  USING INDEX WORKDESK.PK_OW_PUR_ORD_PUB
  ENABLE VALIDATE);


CREATE INDEX WORKDESK.OW_PUR_ORD_PUB_IDX1 ON WORKDESK.OW_PUR_ORD_PUB
(VENDOR_ID)
LOGGING
TABLESPACE WORKDESK_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM OW_PUR_ORD_PUB FOR WORKDESK.OW_PUR_ORD_PUB;


ALTER TABLE WORKDESK.OW_PUR_ORD_PUB ADD (
  CONSTRAINT FK_OW_PUR_ORD_PUB_WORKSHEET 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET_PUB (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_PUR_ORD_PUB TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_PUR_ORD_PUB TO PUBLIC;
