DROP TABLE WORKDESK.OW_PO_PRD_PLANTS CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_PO_PRD_PLANTS
(
  TK_OW         NUMBER(7),
  LINE_NUM      NUMBER(5),
  TK_PRD_PLANT  NUMBER(6)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_PO_PRD_PLANTS TO OMS;
