DROP TABLE WORKDESK.OW_SO_PRD_LINE CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_SO_PRD_LINE
(
  TK_OW            NUMBER(7)                    NOT NULL,
  LINE_NUM         NUMBER(5)                    NOT NULL,
  SELL_PRICE_CASE  NUMBER(15,7),
  SELL_PRICE_WT    NUMBER(15,7),
  SELL_PRICE_UOM   VARCHAR2(6 BYTE)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_SO_PRD_LINE IS 'This table includes all product lines for Worksheets/Templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_SO_PRD_LINE.TK_OW IS 'This is the id for the worksheet.';

COMMENT ON COLUMN WORKDESK.OW_SO_PRD_LINE.LINE_NUM IS 'This is the worksheet line number.';

COMMENT ON COLUMN WORKDESK.OW_SO_PRD_LINE.SELL_PRICE_CASE IS 'This is the price per case.';

COMMENT ON COLUMN WORKDESK.OW_SO_PRD_LINE.SELL_PRICE_WT IS 'This is the price per UOM (other than case)';

COMMENT ON COLUMN WORKDESK.OW_SO_PRD_LINE.SELL_PRICE_UOM IS 'Selling Price UOM';


CREATE UNIQUE INDEX WORKDESK.PK_OW_SO_PRD_LINE ON WORKDESK.OW_SO_PRD_LINE
(TK_OW, LINE_NUM)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_SO_PRD_LINE ADD (
  CONSTRAINT PK_OW_SO_PRD_LINE
  PRIMARY KEY
  (TK_OW, LINE_NUM)
  USING INDEX WORKDESK.PK_OW_SO_PRD_LINE
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_SO_PRD_LINE FOR WORKDESK.OW_SO_PRD_LINE;


ALTER TABLE WORKDESK.OW_SO_PRD_LINE ADD (
  CONSTRAINT FK_OW_SO_PRD_LINE_SALE_ORD 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_SALE_ORD (TK_OW)
  ENABLE VALIDATE
,  CONSTRAINT FK_OW_WS_SO_PRD_LINE 
  FOREIGN KEY (TK_OW, LINE_NUM) 
  REFERENCES WORKDESK.OW_WS_PRD_LINE (TK_OW, LINE_NUM)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_SO_PRD_LINE TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_SO_PRD_LINE TO PUBLIC;
