DROP TABLE WORKDESK.OW_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_TEMPLATE
(
  TK_OW  NUMBER(7)                              NOT NULL
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_TEMPLATE IS 'This table includes the ids of templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_TEMPLATE.TK_OW IS 'This is the id for the Template.';


CREATE UNIQUE INDEX WORKDESK.PK_OW_TEMPLATE ON WORKDESK.OW_TEMPLATE
(TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_TEMPLATE ADD (
  CONSTRAINT PK_OW_TEMPLATE
  PRIMARY KEY
  (TK_OW)
  USING INDEX WORKDESK.PK_OW_TEMPLATE
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_TEMPLATE FOR WORKDESK.OW_TEMPLATE;


ALTER TABLE WORKDESK.OW_TEMPLATE ADD (
  CONSTRAINT FK_OW_TEMPLATE_WORKSHEET 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_TEMPLATE TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_TEMPLATE TO PUBLIC;
