DROP TABLE WORKDESK.OW_USER_PREF CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_USER_PREF
(
  TK_PREF      NUMBER,
  TK_EMPLOYEE  NUMBER                           NOT NULL,
  VALUE        VARCHAR2(1024 BYTE)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WORKDESK.OW_USER_PREF ON WORKDESK.OW_USER_PREF
(TK_PREF, TK_EMPLOYEE)
LOGGING
TABLESPACE WORKDESK_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_USER_PREF ADD (
  CONSTRAINT OW_USER_PREF
  PRIMARY KEY
  (TK_PREF, TK_EMPLOYEE)
  USING INDEX WORKDESK.OW_USER_PREF
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_USER_PREF FOR WORKDESK.OW_USER_PREF;


ALTER TABLE WORKDESK.OW_USER_PREF ADD (
  CONSTRAINT OW_USER_PREF_FK_TK_PREF 
  FOREIGN KEY (TK_PREF) 
  REFERENCES ATISPROD.APP_USER_PREFS (TK_PREF)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON WORKDESK.OW_USER_PREF TO ATISPROD;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON WORKDESK.OW_USER_PREF TO OMS;
