DROP TABLE WORKDESK.OW_WS_FOREX_PUB CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_WS_FOREX_PUB
(
  TK_OW            NUMBER(7)                    NOT NULL,
  BANK_DESCR       VARCHAR2(50 BYTE),
  EXCHANGE_RATE    NUMBER(13,7),
  EXCHANGE_AMOUNT  NUMBER(13,2),
  CONTRACT_NUMBER  VARCHAR2(20 BYTE),
  VALUATION_DATE   DATE
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_WS_FOREX_PUB IS 'This table includes all Foreign Exchange records for published Worksheets/Templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX_PUB.TK_OW IS 'This is the id for the Worksheet/Template.';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX_PUB.BANK_DESCR IS 'Bank';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX_PUB.EXCHANGE_RATE IS 'Rate';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX_PUB.EXCHANGE_AMOUNT IS 'Total Value (in foreign currency)';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX_PUB.CONTRACT_NUMBER IS 'Contract #';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX_PUB.VALUATION_DATE IS 'Valuation Date';


CREATE UNIQUE INDEX WORKDESK.PK_OW_WS_FOREX_PUB ON WORKDESK.OW_WS_FOREX_PUB
(TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_WS_FOREX_PUB ADD (
  CONSTRAINT PK_OW_WS_FOREX_PUB
  PRIMARY KEY
  (TK_OW)
  USING INDEX WORKDESK.PK_OW_WS_FOREX_PUB
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_WS_FOREX_PUB FOR WORKDESK.OW_WS_FOREX_PUB;


ALTER TABLE WORKDESK.OW_WS_FOREX_PUB ADD (
  CONSTRAINT FK_OW_WS_FOREX_PUB_WORKSHEET 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET_PUB (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_FOREX_PUB TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_FOREX_PUB TO PUBLIC;
