DROP TABLE WORKDESK.OW_WS_ACCRUAL CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_WS_ACCRUAL
(
  TK_OW          NUMBER(7)                      NOT NULL,
  COST_TYPE_ID   VARCHAR2(7 BYTE)               NOT NULL,
  SEQ            VARCHAR2(5 BYTE)               NOT NULL,
  ACCRUAL_DESCR  VARCHAR2(35 BYTE),
  AMOUNT         NUMBER(8,2)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_WS_ACCRUAL IS 'This table includes all accruals for Worksheets/Templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_WS_ACCRUAL.TK_OW IS 'This is the id for the Worksheet/Template.';

COMMENT ON COLUMN WORKDESK.OW_WS_ACCRUAL.COST_TYPE_ID IS 'This is the id of the accrual (eg. Ocean, Inland, etc.)';

COMMENT ON COLUMN WORKDESK.OW_WS_ACCRUAL.SEQ IS 'This is the sequence/count of the accrual type (eg. Ocean 1, Ocean 2, etc)';

COMMENT ON COLUMN WORKDESK.OW_WS_ACCRUAL.ACCRUAL_DESCR IS 'Accrual Description';

COMMENT ON COLUMN WORKDESK.OW_WS_ACCRUAL.AMOUNT IS 'Accrual Amount';


CREATE UNIQUE INDEX WORKDESK.PK_OW_WS_ACCRUAL ON WORKDESK.OW_WS_ACCRUAL
(TK_OW, COST_TYPE_ID, SEQ)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_WS_ACCRUAL ADD (
  CONSTRAINT PK_OW_WS_ACCRUAL
  PRIMARY KEY
  (TK_OW, COST_TYPE_ID, SEQ)
  USING INDEX WORKDESK.PK_OW_WS_ACCRUAL
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_WS_ACCRUAL FOR WORKDESK.OW_WS_ACCRUAL;


ALTER TABLE WORKDESK.OW_WS_ACCRUAL ADD (
  CONSTRAINT FK_OW_WS_ACCRUAL_WORKSHEET 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_ACCRUAL TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_ACCRUAL TO PUBLIC;
