DROP TABLE WORKDESK.OW_WORKSHEET_PUB CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_WORKSHEET_PUB
(
  TK_OW               NUMBER(7)                 NOT NULL,
  TYPE                VARCHAR2(56 BYTE)         NOT NULL,
  DESCRIPTION         VARCHAR2(256 BYTE)        NOT NULL,
  SET_WRKSHT_NUM      NUMBER(7),
  VERSION_NUM         NUMBER(5)                 NOT NULL,
  STATUS              VARCHAR2(30 BYTE)         NOT NULL,
  DEST_TK_CNTRY       NUMBER(5),
  INSP_TK_CNTRY       NUMBER(5),
  PLANT               VARCHAR2(100 BYTE),
  CO_TK_ORG           NUMBER(15),
  CURRENCY_CODE       VARCHAR2(15 BYTE)         NOT NULL,
  WT_UOM              VARCHAR2(6 BYTE)          NOT NULL,
  CREATION_DATE       DATE                      NOT NULL,
  CREATED_BY          NUMBER(15)                NOT NULL,
  LAST_UPDATE_DATE    DATE,
  LAST_UPDATED_BY     NUMBER(15),
  INIT_TK_OW          NUMBER(7)                 NOT NULL,
  OWNER               NUMBER(15),
  NOTIFY_SUBJECT      VARCHAR2(100 BYTE),
  ODS                 VARCHAR2(1 BYTE)          DEFAULT 'N'                   NOT NULL,
  DEST_PORT           VARCHAR2(50 BYTE),
  POSITION_PURCHASE   VARCHAR2(1 BYTE)          DEFAULT 'N'                   NOT NULL,
  PURCHASE_DECISION   VARCHAR2(128 BYTE)        DEFAULT 'UNPOSITIONED'        NOT NULL,
  POSITION_PROCESSED  DATE,
  PROVINCE            NUMBER(5)                 DEFAULT 0                     NOT NULL,
  TK_SUP_OFFER        NUMBER(15),
  NEW_OW              CHAR(1 BYTE),
  ORIG_TK_CNTRY       NUMBER(5)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_WORKSHEET_PUB IS 'This table includes the header information for published worksheets/templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.TK_OW IS 'This is the id for the Worksheet/Template.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.TYPE IS 'Worksheet Type (Template or Worksheet)';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.DESCRIPTION IS 'Description - Description/Name for the worksheet/template.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.SET_WRKSHT_NUM IS 'Worksheet Number to identify the Worksheet.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.VERSION_NUM IS 'Version Number';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.STATUS IS 'Status of the Worksheet (Published, etc)';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.DEST_TK_CNTRY IS 'Destination Country - This is the destination country.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.INSP_TK_CNTRY IS 'Inspected For - This is the inspected for country.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.CO_TK_ORG IS 'Company';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.LAST_UPDATED_BY IS 'User id    of the person that last updated the record.';

COMMENT ON COLUMN WORKDESK.OW_WORKSHEET_PUB.PROVINCE IS 'State or province from which product originates.';


CREATE UNIQUE INDEX WORKDESK.PK_OW_WORKSHEET_PUB ON WORKDESK.OW_WORKSHEET_PUB
(TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_WORKSHEET_PUB ADD (
  CONSTRAINT PK_OW_WORKSHEET_PUB
  PRIMARY KEY
  (TK_OW)
  USING INDEX WORKDESK.PK_OW_WORKSHEET_PUB
  ENABLE VALIDATE);


CREATE INDEX WORKDESK.IDX_WORKSHEET_OWNER ON WORKDESK.OW_WORKSHEET_PUB
(OWNER)
LOGGING
TABLESPACE WORKDESK_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX WORKDESK.I_OW_WORKSHEET_PUB_INIT_TK_OW ON WORKDESK.OW_WORKSHEET_PUB
(INIT_TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM OW_WORKSHEET_PUB FOR WORKDESK.OW_WORKSHEET_PUB;


ALTER TABLE WORKDESK.OW_WORKSHEET_PUB ADD (
  CONSTRAINT FK_OW_STATUS_PUB_WORKSHEET 
  FOREIGN KEY (STATUS) 
  REFERENCES WORKDESK.OW_WS_STATUS (STATUS)
  ENABLE VALIDATE
,  CONSTRAINT FK_OW_WS_TYPE_PUB_WORKSHEET 
  FOREIGN KEY (TYPE) 
  REFERENCES WORKDESK.OW_WS_TYPE (TYPE)
  ENABLE VALIDATE
,  CONSTRAINT FK_PURCHASE_DECISION_PUB 
  FOREIGN KEY (PURCHASE_DECISION) 
  REFERENCES WORKDESK.PURCHASE_DECISION (DECISION_TYPE)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WORKSHEET_PUB TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WORKSHEET_PUB TO PUBLIC;
