DROP TABLE WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB
(
  TK_OW            NUMBER(7)                    NOT NULL,
  NOTIFY_COMMENTS  VARCHAR2(1000 BYTE)          NOT NULL
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WORKDESK.PK_OW_WS_NOTIFY_COMMENTS_PUB ON WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB
(TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB ADD (
  CONSTRAINT PK_OW_WS_NOTIFY_COMMENTS_PUB
  PRIMARY KEY
  (TK_OW)
  USING INDEX WORKDESK.PK_OW_WS_NOTIFY_COMMENTS_PUB
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_WS_NOTIFY_COMMENTS_PUB FOR WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB;


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_NOTIFY_COMMENTS_PUB TO PUBLIC;
