DROP TABLE WORKDESK.OW_WS_FOREX CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_WS_FOREX
(
  TK_OW            NUMBER(7)                    NOT NULL,
  BANK_DESCR       VARCHAR2(50 BYTE),
  EXCHANGE_RATE    NUMBER(13,7),
  EXCHANGE_AMOUNT  NUMBER(13,2),
  CONTRACT_NUMBER  VARCHAR2(20 BYTE),
  VALUATION_DATE   DATE
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_WS_FOREX IS 'This table includes all Foreign Exchange records for Worksheets/Templates created through Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX.TK_OW IS 'This is the id for the Worksheet/Template.';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX.BANK_DESCR IS 'Bank';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX.EXCHANGE_RATE IS 'Rate';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX.EXCHANGE_AMOUNT IS 'Total Value (in foreign currency)';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX.CONTRACT_NUMBER IS 'Contract #';

COMMENT ON COLUMN WORKDESK.OW_WS_FOREX.VALUATION_DATE IS 'Valuation Date';


CREATE UNIQUE INDEX WORKDESK.PK_OW_WS_FOREX ON WORKDESK.OW_WS_FOREX
(TK_OW)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_WS_FOREX ADD (
  CONSTRAINT PK_OW_WS_FOREX
  PRIMARY KEY
  (TK_OW)
  USING INDEX WORKDESK.PK_OW_WS_FOREX
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_WS_FOREX FOR WORKDESK.OW_WS_FOREX;


ALTER TABLE WORKDESK.OW_WS_FOREX ADD (
  CONSTRAINT FK_OW_WS_FOREX_WORKSHEET 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_FOREX TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_FOREX TO PUBLIC;
