DROP TABLE WORKDESK.OW_WS_RECIPIENT CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.OW_WS_RECIPIENT
(
  TK_OW           NUMBER(7)                     NOT NULL,
  RECIPIENT_TYPE  VARCHAR2(56 BYTE)             NOT NULL,
  TK_EMPLOYEE     NUMBER(15)                    NOT NULL
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.OW_WS_RECIPIENT IS 'This table contains employees designated to receive worksheet documents from Order Workdesk.';

COMMENT ON COLUMN WORKDESK.OW_WS_RECIPIENT.TK_OW IS 'The ID of the Worksheet/Template.';

COMMENT ON COLUMN WORKDESK.OW_WS_RECIPIENT.RECIPIENT_TYPE IS 'The type of recipient.';

COMMENT ON COLUMN WORKDESK.OW_WS_RECIPIENT.TK_EMPLOYEE IS 'The employee ID of the recipient.';


CREATE UNIQUE INDEX WORKDESK.PK_OW_WS_RECIPIENT ON WORKDESK.OW_WS_RECIPIENT
(TK_OW, RECIPIENT_TYPE, TK_EMPLOYEE)
LOGGING
TABLESPACE WORKDESK_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.OW_WS_RECIPIENT ADD (
  CONSTRAINT PK_OW_WS_RECIPIENT
  PRIMARY KEY
  (TK_OW, RECIPIENT_TYPE, TK_EMPLOYEE)
  USING INDEX WORKDESK.PK_OW_WS_RECIPIENT
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM OW_WS_RECIPIENT FOR WORKDESK.OW_WS_RECIPIENT;


ALTER TABLE WORKDESK.OW_WS_RECIPIENT ADD (
  CONSTRAINT FK_OW_WS_RECIPIENT_TYPE 
  FOREIGN KEY (RECIPIENT_TYPE) 
  REFERENCES WORKDESK.OW_RECIPIENT_TYPE (TYPE)
  ENABLE VALIDATE
,  CONSTRAINT FK_OW_WS_RECIPIENT_WORKSHEET 
  FOREIGN KEY (TK_OW) 
  REFERENCES WORKDESK.OW_WORKSHEET (TK_OW)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_RECIPIENT TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.OW_WS_RECIPIENT TO PUBLIC;
