DROP TABLE WORKDESK.PURCHASE_DECISION CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.PURCHASE_DECISION
(
  DECISION_TYPE     VARCHAR2(128 BYTE)          NOT NULL,
  DESCRIPTION       VARCHAR2(255 BYTE),
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER(15)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE WORKDESK.PURCHASE_DECISION IS 'This table contains all valid purchase decision types.';

COMMENT ON COLUMN WORKDESK.PURCHASE_DECISION.DECISION_TYPE IS 'Type of decision.';

COMMENT ON COLUMN WORKDESK.PURCHASE_DECISION.DESCRIPTION IS 'Detailed description of the purchase decision.';

COMMENT ON COLUMN WORKDESK.PURCHASE_DECISION.CREATION_DATE IS 'Date when record was created.';

COMMENT ON COLUMN WORKDESK.PURCHASE_DECISION.CREATED_BY IS 'User id   of the person that created the record.';

COMMENT ON COLUMN WORKDESK.PURCHASE_DECISION.LAST_UPDATE_DATE IS 'Date when record was last updated.';

COMMENT ON COLUMN WORKDESK.PURCHASE_DECISION.LAST_UPDATED_BY IS 'User id of the person that last updated the record.';


CREATE UNIQUE INDEX WORKDESK.PK_PURCHASE_DECISION ON WORKDESK.PURCHASE_DECISION
(DECISION_TYPE)
LOGGING
TABLESPACE WORKDESK_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WORKDESK.PURCHASE_DECISION ADD (
  CONSTRAINT PK_PURCHASE_DECISION
  PRIMARY KEY
  (DECISION_TYPE)
  USING INDEX WORKDESK.PK_PURCHASE_DECISION
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM PURCHASE_DECISION FOR WORKDESK.PURCHASE_DECISION;


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.PURCHASE_DECISION TO OMS;

GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.PURCHASE_DECISION TO PUBLIC;
