DROP TABLE WORKDESK.TEST_INTERAL_LOG_ERROR CASCADE CONSTRAINTS;

CREATE TABLE WORKDESK.TEST_INTERAL_LOG_ERROR
(
  ID_LOG      NUMBER(10),
  TEXT_LOG    VARCHAR2(4000 BYTE),
  DATE_LOG    DATE,
  NUMBER_LOG  NUMBER(10),
  USER_LOG    VARCHAR2(4000 BYTE)
)
TABLESPACE WORKDESK_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


GRANT DELETE, INSERT, SELECT, UPDATE ON WORKDESK.TEST_INTERAL_LOG_ERROR TO OMS;
