DROP PACKAGE WORKDESK.APX_WORKDESK_GET_OFFER;

CREATE OR REPLACE PACKAGE WORKDESK."APX_WORKDESK_GET_OFFER" AS 
CONST_PACKAGE_NAME CONSTANT VARCHAR2(100) := 'APX_WORKDESK_GET_OFFER';


PROCEDURE OW_WORKSHEET_INSERT_FROM_OFFER;

END APX_WORKDESK_GET_OFFER;
/


GRANT EXECUTE ON WORKDESK.APX_WORKDESK_GET_OFFER TO OMS;
