DROP PACKAGE WORKDESK.APX_ADM_PO;

CREATE OR REPLACE PACKAGE WORKDESK."APX_ADM_PO" AS 

  FUNCTION Get_Product_List_Offer_List(
                p_ow_tk IN NUMBER,
                p_max_product IN NUMBER DEFAULT NULL,
                p_status IN VARCHAR2 DEFAULT 'ACTIVE'
                )RETURN VARCHAR2;


END APX_ADM_PO;
/


GRANT EXECUTE ON WORKDESK.APX_ADM_PO TO OMS;
